# -*- coding: utf-8 -*-
"""python_project_22_4_23&23_4_23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pgv20J44gOa0OwAtoCGuFBBK_rybc778
"""

import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
# import required libraries for reading & graphical representaion of data

from google.colab import files
uploaded = files.upload()

import pandas as pd
housing=pd.read_excel('housing.xlsx')
# using pandas to read the data file which is an excel file
housing.head() 
# head is used for read first five records

housing.info()

"""##Comments.

1--The above data shows total 20640 entries.
2--shows default indexing i,e 0 to 20639.
3--shows total 10 column for different parameters.
4--all data vlaue are numerical float type except ocean_proximity which is text 5--type i,e object.
6--total_bedrooms column has 207 null values/missing values.
7--total memory usage is 1.6+ MB.

Q.1 What is the average median income of the data set and check the distribution of data using appropriate plots. Please explain the distribution of the plot.
"""

income_mean = housing['median_income'].mean() 
print(income_mean)
# calculated medain income mean and stored it in a variable as income_mean

sns.distplot(a=housing.latitude, color='blue', 
             hist_kws={"edgecolor": 'red'})
#using density histogram plot to see the skewness in data as density plot is modified verion of histogram

sns.distplot(a=housing.longitude, color='blue',
             hist_kws={"edgecolor": 'red'})
#using density histogram plot to see the skewness in data as density plot is modified verion of histogram

sns.distplot(a=housing.housing_median_age, color='blue',
             hist_kws={"edgecolor": 'red'})
#using density histogram plot to see the skewness in data as density plot is modified verion of histogram

sns.distplot(a=housing.median_income, color='blue',
             hist_kws={"edgecolor": 'red'})
#using density histogram plot to see the skewness in data as density plot is modified verion of histogram

sns.distplot(a=housing.median_house_value, color='blue',
             hist_kws={"edgecolor": 'red'})
#using density histogram plot to see the skewness in data as density plot is modified verion of histogram

sns.distplot(a=housing.total_rooms, color='blue',
             hist_kws={"edgecolor": 'red'})
#using density histogram plot to see the skewness in data as density plot is modified verion of histogram

sns.distplot(a=housing.total_bedrooms, color='blue',
             hist_kws={"edgecolor": 'red'})
#using density histogram plot to see the skewness in data as density plot is modified verion of histogram

sns.distplot(a=housing.population, color='blue',
             hist_kws={"edgecolor": 'red'})
#using density histogram plot to see the skewness in data as density plot is modified verion of histogram

sns.distplot(a=housing.households, color='blue',
             hist_kws={"edgecolor": 'red'})
#using density histogram plot to see the skewness in data as density plot is modified verion of histogram
# showing right or positive skewned graph

"""comments
---Observation :- From the above plot,it is to be noted that the outliers are present for longitude, latitude, housing_median_age and median_house_value.

-while total_rooms,total_bedrooms,population,households,median_income are of Right skewed

Q.2 Draw an appropriate plot to see the distribution of housing_median_age and explain your observations.
"""

plt.hist(housing["housing_median_age"],color='pink')  #Histogram is used to see the distribution of a numerical value.
plt.title("housing_median_age- Histogram plot")    # x-axis=housing_median_age,y-axis=Frequencies
plt.xlabel("housing_median_age")
plt.ylabel("Frequencies")
plt.grid(True)
plt.show()

"""##Observation:- From the above histogram plot we can come to the analysis that it is distributed symmetrically. frequency is highest at the age of 35.

Q.3 Show with the help of visualization, how median_income and median_house_values are related?
"""

sns.scatterplot(x="median_house_value",y="median_income",data=housing)
 ##scatter plot gives a relation between two numerical values.
 #x-axis median_house_value  #Y axis median_income

"""##Observation:- 1.From the above observation it is to be analysed that with an increase in the median_house_value there is also an increase in the median income. 2.Outlier is present in median_house_value which is shown in the graph, Therefore,median_house_value is directly proportional to median income.

Q.4 Create a data set by deleting the corresponding examples from the data set for which total_bedrooms are not available.
"""

housing[housing.isnull().any(axis=1)]
#The isnull() method returns a DataFrame object where all the values are 
#replaced with a Boolean value True for NULL values, and otherwise False.
#Here missing values are denoted by NaN

"""##Observation:- In the above code,missing values are identified by using isnull()method.This missing values are identified in the column 'total_bedrooms' and the mising values is denoted by NAN.

Q.5 Create a data set by filling the missing data with the mean value of the total_bedrooms in the original data set.
"""

housing["total_bedrooms"]=housing["total_bedrooms"].fillna(housing['total_bedrooms'].mean())
housing

"""##Observation:- In the above code,a new dataset had been created where the missing values in the 'total_bedrooms'which are denoted by NaN are replaced with the mean value of the 'total_bedrooms'.

Q.6 Write a programming construct (create a user defined function) to calculate the median value of the data set wherever required.
"""

housing.median()

"""Q.7 Plot latitude versus longitude and explain your observations."""

sns.scatterplot(x='latitude',y='longitude',data=housing)  
#Scatter plot gives a relationship between two numerical values.
 #x-axis = latitude #y-axis = longitude

"""##Obervation:- From the above plot,it is to be noted that with an decrease in longitude,latitude is increased.From this point of view,it is to be known that latitude and longitude are not dependent on each other.From this we can say that longitude is inversely proportional to latitude.

From the above plot it is to be noted that latitude vs longitude has negative correlation as here y-axis is increasing while x-axis is decreasing,i.e., both are moving in an opposite direction.

Q.8 Create a data set for which the ocean_proximity is ‘Near ocean’.
"""

near_by=housing.loc[housing["ocean_proximity"]=="NEAR OCEAN"] 
# loc is an label based method which is used to select rows and columns by Names/Labels.
print(near_by)

"""##Obervation :- A data set is created were ocean proximity is near ocean

Q.9 Find the mean and median of the median income for the data set created in question 8.
"""

near_by['median_income'].mean() #getting mean of near_by as created in Q.8

near_by['median_income'].median() #getting medain of near_by as created in Q.8

"""##Observation:- The mean and median value of the 'median_income'in the created new dataset are:4.005784 and 3.64705 respectively.

10.Please create a new column named total_bedroom_size. If size 10 or less. It should be quoted as small. If the size is 11 or more but 1000 less, it should be medium, otherwise it should be large.
"""

size= [
              (housing['total_bedrooms'] <=10),
              (housing['total_bedrooms'] >=11)&(housing['total_bedrooms'] <=1000),
              (housing['total_bedrooms'] > 1000)
             ]
values = ['small','medium','large']

housing['total_bedrooms_size']=housing.select(size,values)

housing

"""##In the above data set a new column named total_bedroom_size had been added.Where the total_bedroom_size had been compared to the total_bedrooms while mentioning about the sizes of the total_bedroom_size,where:

1--If the total_bedroom_size <=10 it is indicated as "small" If the total_bedroom_size >=11 or <=1000 it is indicated as "medium" If the total_bedroom_size >1000 it is indicated as "large"

Conclusion

1.All the features present in this dataset are of float type except ocean_proximity which is of object datatype,

2.plot between median_income vs median_house_values is directly proportional to each other as it has positive correlation.

3.plot between latitude and longitude is inversely proportional to each other as within increase in latitude,there is decrease in longitude.Therefore ,it has a negative correlation.
"""